# Generated by Django 5.2.4 on 2025-08-12 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
            ],
        ),
    ]
