# Generated by Django 5.2.4 on 2025-08-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_active_products_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_stock',
        ),
    ]
