# Generated by Django 5.2.4 on 2025-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
